version: '3.7'
volumes:
  dbdata:
networks:
  marketplace:
services:
  db:
    image: mysql:8
    container_name: marketplace_db
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: marketplace
    ports:
      - 3306:3306
    networks:
      - marketplace
  app:
    build: .
    image: marketplace_api
    container_name: marketplace_api
    volumes:
      - ./:/app
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    ports:
      - 80:80
    networks:
      - marketplace
    depends_on:
      - db
