version: '3.7'
volumes:
  dbdata:
networks:
  sbf:
services:
  db:
    image: mysql:8
    container_name: sbf_db
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sbf
    ports:
      - 3306:3306
    networks:
      - sbf
  app:
    build: .
    image: sbf_api
    container_name: sbf_api
    volumes:
      - ./:/app
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    ports:
      - 80:80
    networks:
      - sbf
    depends_on:
      - db
